import { vi } from 'vitest';
import { IBoardPagePageObject, SwimlaneElement } from './BoardPage';

export const BoardPagePageObjectMock: IBoardPagePageObject = {
  selectors: {
    pool: '#ghx-pool',
    issue: '.ghx-issue',
    flagged: '.ghx-flagged',
    grabber: '.ghx-grabber',
    grabberTransparent: '.ghx-grabber-transparent',
    sidebar: '.ghx-sidebar',
    column: '.ghx-column',
    columnHeader: '.ghx-column-header',
    columnTitle: '.ghx-column-title',
    daysInColumn: '.ghx-days',
    swimlaneHeader: '.ghx-swimlane-header',
    swimlaneRow: '.ghx-swimlane',
    avatarImg: '.ghx-avatar-img',
    issueType: '.ghx-type',
    parentGroup: '.ghx-parent-group',
  },
  classlist: {
    flagged: 'ghx-flagged',
  },
  getColumns: () => ['To Do', 'In Progress', 'Done'],
  listenCards: () => () => {},
  getColumnOfIssue: () => '',
  getDaysInColumn: () => null,
  hideDaysInColumn: () => {},
  getHtml: () => '',
  getSwimlanes: (): SwimlaneElement[] => [],
  getSwimlaneHeader: () => null,
  getIssueCountInSwimlane: () => 0,
  getIssueCountByColumn: () => [],
  getIssueCountForColumns: () => 0,
  insertSwimlaneComponent: () => {},
  removeSwimlaneComponent: () => {},
  highlightSwimlane: () => {},
  getOrderedColumnIds: () => [],
  getOrderedColumns: vi.fn(() => []),
  getColumnHeaderElement: () => null,
  getSwimlaneIds: () => [],
  getIssueCountInColumn: () => 0,
  styleColumnHeader: () => {},
  resetColumnHeaderStyles: () => {},
  insertColumnHeaderHtml: () => {},
  removeColumnHeaderElements: () => {},
  highlightColumnCells: () => {},
  resetColumnCellStyles: () => {},
  getIssueElements: () => [],
  getIssueElementsInColumn: () => [],
  getAssigneeFromIssue: () => null,
  getIssueTypeFromIssue: () => null,
  getColumnIdOfIssue: () => null,
  getColumnIdFromColumn: () => null,
  getSwimlaneIdOfIssue: () => null,
  hasCustomSwimlanes: () => false,
  getColumnElements: () => [],
  getColumnsInSwimlane: () => [],
  getParentGroups: () => [],
  countIssueVisibility: () => ({ total: 0, hidden: 0 }),
  setIssueBackgroundColor: () => {},
  resetIssueBackgroundColor: () => {},
  setIssueVisibility: () => {},
  setSwimlaneVisibility: () => {},
  setParentGroupVisibility: () => {},
  getSelectedIssueKey: () => null,
};
